services:
  proof-server:
    image: "midnightnetwork/proof-server:6.1.0-alpha.5"
    command: ["midnight-proof-server", "--network", "undeployed"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
